//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MessageService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Message()
        {
            this.MessageToRecipient = new HashSet<MessageToRecipient>();
        }
    
        public string Id { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public bool IsSent { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MessageToRecipient> MessageToRecipient { get; set; }
        public virtual Message Message1 { get; set; }
        public virtual Message Message2 { get; set; }
        public virtual Message Message11 { get; set; }
        public virtual Message Message3 { get; set; }
        public virtual Message Message12 { get; set; }
        public virtual Message Message4 { get; set; }
    }
}
